/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.GrnModel;
import org.apache.log4j.Logger;

/**
 *
 * @author EZIO AUDITORY
 */
public class GrnManager extends javax.swing.JFrame {

    /**
     * Creates new form GrnManager
     */
    private GrnModel grnModel;
    private LoadSupplierDialog loadSupplierDialog;
    private LoadProductDialog loadProductDialog;
    static Logger logger = Logger.getLogger(GrnManager.class.getName());

    DefaultTableModel grnTableModel;
    DefaultTableModel grnTableModelFull;
    DefaultTableModel grnItemTableModelFull;

    int supplierNo;

    public GrnManager() {
        initComponents();
        logger.debug("Access to GrnManager.java");

        grnTableModel = (DefaultTableModel) grnTable.getModel();
        grnTableModelFull = (DefaultTableModel) grnTableFull.getModel();
        grnItemTableModelFull = (DefaultTableModel) grnItemTableFull.getModel();

        grnModel = new GrnModel();
        loadSupplierDialog = new LoadSupplierDialog(this, rootPaneCheckingEnabled);
        loadProductDialog = new LoadProductDialog(this, rootPaneCheckingEnabled);

        grnModel.loadGrnTableFull("", grnTableModelFull);
        grnModel.loadGrnItemTableFull("", grnItemTableModelFull);

        grnNoLoad();

        grnDateChooser.setDate(new java.util.Date());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        grnNoField = new javax.swing.JTextField();
        grnDateChooser = new com.toedter.calendar.JDateChooser();
        supplierNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grnTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        discountField = new javax.swing.JTextField();
        totalAmountField = new javax.swing.JTextField();
        netAmountField = new javax.swing.JTextField();
        vatField = new javax.swing.JTextField();
        itemCountField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        addRowButton = new javax.swing.JButton();
        deleteRowButton = new javax.swing.JButton();
        saveGrnButton = new javax.swing.JButton();
        newGrnButton = new javax.swing.JButton();
        GrnButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        keywordFieldFull = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        grnTableFull = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        grnButton1 = new javax.swing.JButton();
        grnHistoryButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        keywordFieldFull1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        grnItemTableFull = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        grnItemHistoryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grn Manager");
        setResizable(false);

        grnNoField.setEnabled(false);

        supplierNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierNameFieldMouseClicked(evt);
            }
        });

        jLabel1.setText("GRN No");

        jLabel2.setText("Supplier");

        jLabel3.setText("GRN Date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(grnNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(grnDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                    .addComponent(supplierNameField))
                .addGap(654, 654, 654))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grnNoField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(grnDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        grnTable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        grnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Product", "Unit Sell Price", "Qty", "Unit", "Unit Buy Price", "Discount", "VAT", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grnTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grnTable.setDragEnabled(true);
        grnTable.setRowHeight(30);
        grnTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        grnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grnTableMouseClicked(evt);
            }
        });
        grnTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                grnTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(grnTable);
        if (grnTable.getColumnModel().getColumnCount() > 0) {
            grnTable.getColumnModel().getColumn(0).setMinWidth(25);
            grnTable.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        discountField.setText("0.00");
        discountField.setEnabled(false);

        totalAmountField.setText("0.00");
        totalAmountField.setEnabled(false);

        netAmountField.setText("0.00");
        netAmountField.setEnabled(false);

        vatField.setText("0.00");
        vatField.setEnabled(false);

        itemCountField.setText("0");
        itemCountField.setEnabled(false);

        jLabel4.setText("Item Count");

        jLabel5.setText("Discount");

        jLabel6.setText("VAT");

        jLabel7.setText("Total Amount");

        jLabel8.setText("Net Amount");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vatField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalAmountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netAmountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(itemCountField))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCountField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vatField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addRowButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addRowButton.setText("Add Row");
        addRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowButtonActionPerformed(evt);
            }
        });

        deleteRowButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteRowButton.setText("Delete Row");
        deleteRowButton.setEnabled(false);
        deleteRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowButtonActionPerformed(evt);
            }
        });

        saveGrnButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveGrnButton.setText("Save GRN");
        saveGrnButton.setEnabled(false);
        saveGrnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGrnButtonActionPerformed(evt);
            }
        });

        newGrnButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newGrnButton.setText("New");
        newGrnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGrnButtonActionPerformed(evt);
            }
        });

        GrnButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GrnButton.setText("GRN");
        GrnButton.setEnabled(false);
        GrnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(addRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveGrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newGrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveGrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newGrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create GRN", jPanel1);

        keywordFieldFull.setForeground(new java.awt.Color(153, 153, 153));
        keywordFieldFull.setText("Search");
        keywordFieldFull.setToolTipText("Search");
        keywordFieldFull.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                keywordFieldFullFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                keywordFieldFullFocusLost(evt);
            }
        });
        keywordFieldFull.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keywordFieldFullKeyReleased(evt);
            }
        });

        grnTableFull.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grn No", "GRN Date", "Supplier", "Item Count", "Total Discount", "Total Vat", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grnTableFull.setRowHeight(25);
        jScrollPane3.setViewportView(grnTableFull);

        grnButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        grnButton1.setText("GRN");
        grnButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnButton1ActionPerformed(evt);
            }
        });

        grnHistoryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        grnHistoryButton.setText("GRN History");
        grnHistoryButton.setOpaque(false);
        grnHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnHistoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1472, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(keywordFieldFull, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(grnButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grnHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keywordFieldFull, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grnButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grnHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GRN History", jPanel2);

        keywordFieldFull1.setForeground(new java.awt.Color(153, 153, 153));
        keywordFieldFull1.setText("Search");
        keywordFieldFull1.setToolTipText("Search");
        keywordFieldFull1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                keywordFieldFull1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                keywordFieldFull1FocusLost(evt);
            }
        });
        keywordFieldFull1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keywordFieldFull1KeyReleased(evt);
            }
        });

        grnItemTableFull.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grn Item No", "Buy Date", "Product No", "Product Name", "Qty", "Unit", "Unit Buy Price", "Discount", "Vat", "Amount", "Grn No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grnItemTableFull.setRowHeight(25);
        jScrollPane4.setViewportView(grnItemTableFull);

        grnItemHistoryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        grnItemHistoryButton.setText("GRN Item History");
        grnItemHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnItemHistoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 1003, Short.MAX_VALUE)
                        .addComponent(keywordFieldFull1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(grnItemHistoryButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keywordFieldFull1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grnItemHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GRN Items History", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void supplierNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierNameFieldMouseClicked
        // TODO add your handling code here:
        loadSupplierDialog.setVisible(true);

        Object[] supplierData = loadSupplierDialog.getSupplierData();
        supplierNo = (int) supplierData[0];
        supplierNameField.setText((String) supplierData[1]);
        //System.out.println(supplierNo);

    }//GEN-LAST:event_supplierNameFieldMouseClicked

    private void addRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowButtonActionPerformed
        // TODO add your handling code here:
        if (supplierNo != 0 && supplierNameField.getText().length() > 0) {
            grnTableModel.addRow(new Object[]{0, null, 0.00, 0.00, "Number", 0.00, 0.00, 0.00, 0.00});
            deleteRowButton.setEnabled(true);
            saveGrnButton.setEnabled(true);
            itemCountField.setText(String.valueOf(grnTableModel.getRowCount()));
        } else {
            loadSupplierDialog.setVisible(true);
            Object[] supplierData = loadSupplierDialog.getSupplierData();
            supplierNo = (int) supplierData[0];
            supplierNameField.setText((String) supplierData[1]);
        }

    }//GEN-LAST:event_addRowButtonActionPerformed

    private void deleteRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowButtonActionPerformed
        // TODO add your handling code here:
        int rowCount = grnTable.getRowCount();
        int selectedRow = grnTable.getSelectedRow();
        int selectedRowCount = grnTable.getSelectedRowCount();

        if (selectedRowCount == 1) {
            grnTableModel.removeRow(selectedRow);
            if (rowCount == 1) {
                deleteRowButton.setEnabled(false);
                saveGrnButton.setEnabled(false);
            }
        } else {
            //if (rowCount == 0) {
            //JOptionPane.showConfirmDialog(rootPane, "Table is Empty !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            // } else {
            JOptionPane.showConfirmDialog(rootPane, "Please Select any Single Row !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            logger.error("Error: Please Select any Single Row !");
            //}
        }
    }//GEN-LAST:event_deleteRowButtonActionPerformed

    private void grnTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grnTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = grnTable.getSelectedRow();
        int selectedColumn = grnTable.getSelectedColumn();

        if (selectedColumn == 1) {
            loadProductDialog.setVisible(true);

            Object[] productData = loadProductDialog.getProductData();

            Object productNoo = productData[0];
            String productName = (String) productData[1];
            Object productQty = productData[2];
            //int productUnitNo = (int) productData[3];
            Object productUnitName = productData[4];
            Object productUnitSellPrice = productData[5];
            //Object productDiscount = productData[6];
            //Object productTax = productData[7];

            grnTableModel.setValueAt(productNoo, selectedRow, 0);
            grnTableModel.setValueAt(productName, selectedRow, 1);
            grnTableModel.setValueAt(productUnitSellPrice, selectedRow, 2);
            grnTableModel.setValueAt(productQty, selectedRow, 3);
            grnTableModel.setValueAt(productUnitName, selectedRow, 4);
            grnTableModel.setValueAt(0.00, selectedRow, 5);
            grnTableModel.setValueAt(0.00, selectedRow, 6);
            grnTableModel.setValueAt(0.00, selectedRow, 7);
            grnTableModel.setValueAt(0.00, selectedRow, 8);

        } else {

            if ((int) grnTableModel.getValueAt(selectedRow, 0) == 0 || grnTableModel.getValueAt(selectedRow, 1) == null) {

                loadProductDialog.setVisible(true);
                Object[] productData = loadProductDialog.getProductData();

                Object productNoo = productData[0];
                String productName = (String) productData[1];
                Object productQty = productData[2];
                //int productUnitNo = (int) productData[3];
                Object productUnitName = productData[4];
                Object productUnitSellPrice = productData[5];
                //Object productDiscount = productData[6];
                //Object productTax = productData[7];

                grnTableModel.setValueAt(productNoo, selectedRow, 0);
                grnTableModel.setValueAt(productName, selectedRow, 1);
                grnTableModel.setValueAt(productUnitSellPrice, selectedRow, 2);
                grnTableModel.setValueAt(productQty, selectedRow, 3);
                grnTableModel.setValueAt(productUnitName, selectedRow, 4);
                grnTableModel.setValueAt(0.00, selectedRow, 5);
                grnTableModel.setValueAt(0.00, selectedRow, 6);
                grnTableModel.setValueAt(0.00, selectedRow, 7);
                grnTableModel.setValueAt(0.00, selectedRow, 8);
            }
        }
        calculateValues();
    }//GEN-LAST:event_grnTableMouseClicked

    private void grnTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grnTableKeyReleased
        // TODO add your handling code here:
        calculateValues();
    }//GEN-LAST:event_grnTableKeyReleased

    private void saveGrnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGrnButtonActionPerformed
        // TODO add your handling code here:
        int rowCount = grnTableModel.getRowCount();

        boolean checkEmptyRows = false;
        for (int i = 0; i < rowCount; i++) {
            int productNo = (int) grnTableModel.getValueAt(i, 0);
            String productName = (String) grnTableModel.getValueAt(i, 1);
            if (productNo == 0 || productName == null) {
                checkEmptyRows = true;
                break;
            }
        }

        if (checkEmptyRows) {
            JOptionPane.showConfirmDialog(rootPane, "There is some Empty Rows !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            logger.error("Error: There is some Empty Rows !");
        } else {

            String grnNo = grnNoField.getText();
            Date grnDate = grnDateChooser.getDate();
            //supplierNo in hear
            String itemCount = itemCountField.getText();
            String totalDiscount = discountField.getText();
            String totalVat = vatField.getText();
            String totalAmount = totalAmountField.getText();

            String grnResult = grnModel.saveGrn(grnNo, grnDate, supplierNo, itemCount, totalDiscount, totalVat, totalAmount);

            String grnItemResult = null;
            for (int i = 0; i < rowCount; i++) {
                int productNo = (int) grnTableModel.getValueAt(i, 0);
                double unitSellPrice = (double) grnTableModel.getValueAt(i, 2);
                double qty = (double) grnTableModel.getValueAt(i, 3);
                double unitBuyPrice = (double) grnTableModel.getValueAt(i, 5);
                double discount = (double) grnTableModel.getValueAt(i, 6);
                double vat = (double) grnTableModel.getValueAt(i, 7);
                double amount = (double) grnTableModel.getValueAt(i, 8);

                grnItemResult = grnModel.saveGrnItem(productNo, unitSellPrice, qty, unitBuyPrice, discount, vat, amount, grnNo);
            }

            if (grnResult.equals("Success") && grnItemResult.equals("Success")) {
                JOptionPane.showConfirmDialog(rootPane, grnItemResult, "Message", -1, 1);
                GrnButton.setEnabled(true);
                addRowButton.setEnabled(false);
                deleteRowButton.setEnabled(false);
                saveGrnButton.setEnabled(false);
                grnModel.loadGrnTableFull("", grnTableModelFull);
                grnModel.loadGrnItemTableFull("", grnItemTableModelFull);
                logger.debug("Message: " + grnItemResult);
            } else {
                JOptionPane.showConfirmDialog(rootPane, grnItemResult, "Error", -1, JOptionPane.ERROR_MESSAGE);
                logger.error("Error: " + grnItemResult);
            }
        }


    }//GEN-LAST:event_saveGrnButtonActionPerformed

    private void newGrnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGrnButtonActionPerformed
        // TODO add your handling code here:
        int rowCount = grnTableModel.getRowCount();

        grnNoLoad();
        supplierNo = 0;
        supplierNameField.setText("");
        grnDateChooser.setDate(new java.util.Date());

        itemCountField.setText("0");
        discountField.setText("0.00");
        vatField.setText("0.00");
        totalAmountField.setText("0.00");
        netAmountField.setText("0.00");

        addRowButton.setEnabled(true);
        deleteRowButton.setEnabled(false);
        saveGrnButton.setEnabled(false);
        GrnButton.setEnabled(false);

        for (int i = rowCount - 1; i >= 0; i--) {
            grnTableModel.removeRow(i);
        }

        logger.debug("clearFields");
    }//GEN-LAST:event_newGrnButtonActionPerformed

    private void GrnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrnButtonActionPerformed
        // TODO add your handling code here:
        int grnNo = Integer.parseInt(grnNoField.getText());
        new GenerateGrnDialog(this, true, grnNo).setVisible(true);
    }//GEN-LAST:event_GrnButtonActionPerformed

    private void keywordFieldFullFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFullFocusGained
        if (keywordFieldFull.getText().equals("Search")) {
            keywordFieldFull.setText("");
            keywordFieldFull.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_keywordFieldFullFocusGained

    private void keywordFieldFullFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFullFocusLost
        // TODO add your handling code here:
        if (keywordFieldFull.getText().equals("")) {
            keywordFieldFull.setText("Search");
            keywordFieldFull.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_keywordFieldFullFocusLost

    private void keywordFieldFullKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordFieldFullKeyReleased
        // TODO add your handling code here:
        String keywordFull = keywordFieldFull.getText();
        grnModel.loadGrnTableFull(keywordFull, grnTableModelFull);
    }//GEN-LAST:event_keywordFieldFullKeyReleased

    private void grnButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnButton1ActionPerformed
        // TODO add your handling code here:
        int rowCount = grnTableFull.getRowCount();
        int selectedRow = grnTableFull.getSelectedRow();
        int selectedRowCount = grnTableFull.getSelectedRowCount();

        if (selectedRowCount == 1) {
            int grnNo = (int) grnTableModelFull.getValueAt(selectedRow, 0);
            new GenerateGrnDialog(this, true, grnNo).setVisible(true);
        } else {
            if (rowCount == 0) {
                JOptionPane.showConfirmDialog(rootPane, "Table is Empty !", "Error", -1, JOptionPane.ERROR_MESSAGE);
                logger.error("Error: Table is Empty !");
            } else {
                JOptionPane.showConfirmDialog(rootPane, "Please Select any Single Row !", "Error", -1, JOptionPane.ERROR_MESSAGE);
                logger.error("Error: Please Select any Single Row !");
            }
        }


    }//GEN-LAST:event_grnButton1ActionPerformed

    private void grnHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnHistoryButtonActionPerformed
        // TODO add your handling code here:
        new GenerateGrnHistoryDialog(this, true).setVisible(true);
    }//GEN-LAST:event_grnHistoryButtonActionPerformed

    private void keywordFieldFull1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFull1FocusGained
        // TODO add your handling code here:
        if (keywordFieldFull1.getText().equals("Search")) {
            keywordFieldFull1.setText("");
            keywordFieldFull1.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_keywordFieldFull1FocusGained

    private void keywordFieldFull1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFull1FocusLost
        // TODO add your handling code here:
        if (keywordFieldFull1.getText().equals("")) {
            keywordFieldFull1.setText("Search");
            keywordFieldFull1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_keywordFieldFull1FocusLost

    private void keywordFieldFull1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordFieldFull1KeyReleased
        // TODO add your handling code here:
        String keywordFull1 = keywordFieldFull1.getText();
        grnModel.loadGrnItemTableFull(keywordFull1, grnItemTableModelFull);
    }//GEN-LAST:event_keywordFieldFull1KeyReleased

    private void grnItemHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnItemHistoryButtonActionPerformed
        // TODO add your handling code here:
        new GenerateGrnItemHistoryDialog(this, true).setVisible(true);
    }//GEN-LAST:event_grnItemHistoryButtonActionPerformed

    private void grnNoLoad() {
        int loadGrnNo = grnModel.getGrnNo();
        loadGrnNo++;
        grnNoField.setText(new String(loadGrnNo + ""));
    }

    private void calculateValues() {
        int selectedRow = grnTable.getSelectedRow();
        int rowCount = grnTableModel.getRowCount();

        double productQty = (double) grnTableModel.getValueAt(selectedRow, 3);
        double productUnitBuyPrice = (double) grnTableModel.getValueAt(selectedRow, 5);
        double productDiscount = (double) grnTableModel.getValueAt(selectedRow, 6);
        double productVat = (double) grnTableModel.getValueAt(selectedRow, 7);
        double productAmount = (productUnitBuyPrice - productDiscount + productVat) * productQty;

        grnTableModel.setValueAt(productAmount, selectedRow, 8);

        itemCountField.setText(String.valueOf(rowCount));

        double totalDiscount = 0;
        double totalVat = 0;
        double totalAmount = 0;

        for (int i = 0; i < rowCount; i++) {
            double rowQty = (double) grnTableModel.getValueAt(i, 3);

            double rowDiscount = (double) grnTableModel.getValueAt(i, 6);
            totalDiscount += rowDiscount * rowQty;

            double rowVat = (double) grnTableModel.getValueAt(i, 7);
            totalVat += rowVat * rowQty;

            double rowAmount = (double) grnTableModel.getValueAt(i, 8);
            totalAmount += rowAmount;
        }
        discountField.setText(String.valueOf(totalDiscount));
        vatField.setText(String.valueOf(totalVat));
        totalAmountField.setText(String.valueOf(totalAmount));
        netAmountField.setText(String.valueOf(totalAmount));

        logger.debug("calculateValues");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
            UIManager.put("Table.showHorizontalLines", true);
            UIManager.put("Table.showVerticalLines", true);
            UIManager.put("ScrollBar.showButtons", true);
            UIManager.put("ScrollBar.width", 16);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GrnManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GrnManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GrnManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GrnManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrnManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GrnButton;
    private javax.swing.JButton addRowButton;
    private javax.swing.JButton deleteRowButton;
    private javax.swing.JTextField discountField;
    private javax.swing.JButton grnButton1;
    private com.toedter.calendar.JDateChooser grnDateChooser;
    private javax.swing.JButton grnHistoryButton;
    private javax.swing.JButton grnItemHistoryButton;
    private javax.swing.JTable grnItemTableFull;
    private javax.swing.JTextField grnNoField;
    private javax.swing.JTable grnTable;
    private javax.swing.JTable grnTableFull;
    private javax.swing.JTextField itemCountField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField keywordFieldFull;
    private javax.swing.JTextField keywordFieldFull1;
    private javax.swing.JTextField netAmountField;
    private javax.swing.JButton newGrnButton;
    private javax.swing.JButton saveGrnButton;
    private javax.swing.JTextField supplierNameField;
    private javax.swing.JTextField totalAmountField;
    private javax.swing.JTextField vatField;
    // End of variables declaration//GEN-END:variables
}
