/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.SalesModel;
import org.apache.log4j.Logger;

/**
 *
 * @author EZIO AUDITORY
 */
public class LoadInvoiceDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoadInvoiceDialog
     */
    private SalesModel salesModel;
    static Logger logger = Logger.getLogger(LoadInvoiceDialog.class.getName());
    DefaultTableModel invoiceTableModelFull;

    int invoiceNoo;
    double deliveryCharge;

    public LoadInvoiceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        logger.debug("Access to LoadCustomerDialog.java");

        invoiceTableModelFull = (DefaultTableModel) invoiceTableFull.getModel();
        salesModel = new SalesModel();

        salesModel.loadInvoiceTableFullForLoadInvoiceDialog("", invoiceTableModelFull);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        keywordFieldFull = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        invoiceTableFull = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Invoice");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Select Invoice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        keywordFieldFull.setForeground(new java.awt.Color(153, 153, 153));
        keywordFieldFull.setText("Search");
        keywordFieldFull.setToolTipText("Search");
        keywordFieldFull.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                keywordFieldFullFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                keywordFieldFullFocusLost(evt);
            }
        });
        keywordFieldFull.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keywordFieldFullKeyReleased(evt);
            }
        });

        invoiceTableFull.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grn No", "Date", "Supplier", "Item Count", "Delivery Charge", "Total Discount", "Total Vat", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        invoiceTableFull.setRowHeight(25);
        invoiceTableFull.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceTableFullMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(invoiceTableFull);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1462, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1438, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 969, Short.MAX_VALUE)
                            .addComponent(keywordFieldFull, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(keywordFieldFull, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keywordFieldFullFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFullFocusGained
        if (keywordFieldFull.getText().equals("Search")) {
            keywordFieldFull.setText("");
            keywordFieldFull.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_keywordFieldFullFocusGained

    private void keywordFieldFullFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFullFocusLost
        // TODO add your handling code here:
        if (keywordFieldFull.getText().equals("")) {
            keywordFieldFull.setText("Search");
            keywordFieldFull.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_keywordFieldFullFocusLost

    private void keywordFieldFullKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordFieldFullKeyReleased
        // TODO add your handling code here:
        String keywordFull = keywordFieldFull.getText();
        salesModel.loadInvoiceTableFullForLoadInvoiceDialog(keywordFull, invoiceTableModelFull);
    }//GEN-LAST:event_keywordFieldFullKeyReleased

    private void invoiceTableFullMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceTableFullMouseClicked
        // TODO add your handling code here:
        int row = invoiceTableFull.getSelectedRow();
        int invoiceNo = (int) invoiceTableModelFull.getValueAt(row, 0);
        Object[] invoiceData = salesModel.getSelectedInvoiceData(invoiceNo);

        invoiceNoo = (int) invoiceData[0];
        deliveryCharge = (double) invoiceData[1];
 
        this.dispose();
        logger.debug("LoadInvoiceDialog.java Dispose");
    }//GEN-LAST:event_invoiceTableFullMouseClicked

    Object[] getInvoiceData() {
        Object[] rowdata = new Object[]{invoiceNoo, deliveryCharge};
        logger.debug("return rowData");
        return rowdata;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
            UIManager.put("Table.showHorizontalLines", true);
            UIManager.put("Table.showVerticalLines", true);
            UIManager.put("ScrollBar.showButtons", true);
            UIManager.put("ScrollBar.width", 16);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoadInvoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoadInvoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoadInvoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoadInvoiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoadInvoiceDialog dialog = new LoadInvoiceDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable invoiceTableFull;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField keywordFieldFull;
    // End of variables declaration//GEN-END:variables

}
